AllCops:
  Exclude:
    - 'db/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'config/initializers/devise.rb'
  NewCops: enable
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/SwapValues:
  Enabled: true
